import React, { useEffect, useMemo, useState } from 'react';
import {
  ArrowLeft,
  BadgeCheck,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ContactRound,
  Edit,
  Eye,
  FileDown,
  Hash,
  Mail,
  Phone,
  Plus,
  RefreshCw,
  Save,
  Search,
  SlidersHorizontal,
  Tag,
  Trash2,
  X,
} from 'lucide-react';
import { Table } from '@heroui/react';
import StatsCard from '../components/common/StatsCard';
import { PARTY_MASTER_FIELDS, PARTY_MASTER_SECTIONS } from '../data/partyMasterTemplate';
import { useERPStore } from '../store/erpStore';

const todayIsoDate = () => new Date().toISOString().split('T')[0];

const EMPTY_PARTY = PARTY_MASTER_FIELDS.reduce((party, field) => {
  if (field.type === 'select') party[field.key] = field.options?.[0] || '';
  else if (field.key === 'partyEnrollmentDate') party[field.key] = todayIsoDate();
  else party[field.key] = '';
  return party;
}, {});

const TABLE_COLUMNS = PARTY_MASTER_FIELDS
  .filter(field => ['partyName', 'partyCode', 'aliasName'].includes(field.key))
  .map(field => ({
  ...field,
  width: field.wide ? '260px' : field.type === 'date' ? '150px' : field.type === 'select' ? '160px' : '190px',
  align: ['partyCode', 'gstStateCode'].includes(field.key) ? 'center' : 'left',
}));

function FormField({ field, value, onChange, disabled, error }) {
  const inputClass = `w-full px-4 py-3 text-[13px] font-medium rounded-xl text-slate-800 border bg-white transition-all outline-none ${error ? 'border-red-300 focus:border-red-400' : 'border-slate-200 focus:border-emerald-500/50'
    } input-glow disabled:bg-slate-50 disabled:text-slate-500 disabled:cursor-not-allowed`;
  const isLocked = disabled || field.autoGenerated;

  return (
    <label className={`flex flex-col gap-2 ${field.wide ? 'md:col-span-2 xl:col-span-3' : ''}`}>
      <span className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">
        {field.label}
        {field.required && <span className="text-red-500 ml-1">*</span>}
      </span>
      {field.type === 'select' ? (
        <select
          value={value || field.options?.[0] || ''}
          disabled={disabled}
          onChange={(event) => onChange(field.key, event.target.value)}
          className={inputClass}
        >
          {(field.options || []).map(option => (
            <option key={option} value={option}>{option}</option>
          ))}
        </select>
      ) : field.type === 'textarea' ? (
        <textarea
          value={value ?? ''}
          disabled={disabled}
          onChange={(event) => onChange(field.key, event.target.value)}
          className={`${inputClass} min-h-28 resize-y`}
          placeholder={field.label}
        />
      ) : (
        <input
          type={field.type || 'text'}
          value={value ?? ''}
          disabled={isLocked}
          onChange={(event) => onChange(field.key, event.target.value)}
          className={inputClass}
          placeholder={field.autoGenerated ? 'Auto generated on create' : field.label}
        />
      )}
      {field.autoGenerated && !disabled && (
        <span className="text-[11px] font-semibold text-emerald-600">Auto generated and locked</span>
      )}
      {error && <span className="text-xs font-medium text-red-500">{error}</span>}
    </label>
  );
}

function PartyMasterForm({ mode, party, onBack }) {
  const { addPartyMaster, updatePartyMaster, getNextPartyCode } = useERPStore();
  const [form, setForm] = useState(EMPTY_PARTY);
  const [errors, setErrors] = useState({});

  useEffect(() => {
    const nextForm = party
      ? { ...EMPTY_PARTY, ...party }
      : { ...EMPTY_PARTY, partyCode: getNextPartyCode(), partyEnrollmentDate: todayIsoDate() };
    setForm(nextForm);
    setErrors({});
  }, [party, mode, getNextPartyCode]);

  const isView = mode === 'view';
  const isAdd = mode === 'add';
  const groupedFields = PARTY_MASTER_SECTIONS.map(section => ({
    section,
    fields: PARTY_MASTER_FIELDS.filter(field => field.section === section),
  }));

  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));

  const validate = () => {
    const nextErrors = {};
    if (!String(form.partyName || '').trim()) nextErrors.partyName = 'Party name is required';
    setErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const submit = (event) => {
    event.preventDefault();
    if (!validate()) return;
    if (isAdd) addPartyMaster(form);
    else updatePartyMaster(party.id, form);
    onBack();
  };

  return (
    <div className="animate-slide-up">
      <div className="glass-card rounded-2xl shadow-xl overflow-hidden">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 px-6 py-5 border-b border-slate-100 bg-slate-50/80">
          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              className="w-11 h-11 rounded-xl bg-white border border-slate-200 text-slate-600 hover:text-emerald-600 hover:bg-emerald-50 hover:border-emerald-100 flex items-center justify-center transition-all"
              title="Back to table"
            >
              <ArrowLeft size={20} />
            </button>
            <div className="w-12 h-12 rounded-2xl flex items-center justify-center bg-emerald-50 border border-emerald-200 shadow-lg shadow-emerald-500/10">
              {isView ? <Eye size={24} className="text-emerald-600" /> : <ContactRound size={24} className="text-emerald-600" />}
            </div>
            <div>
              <h2 className="text-xl font-black text-slate-800 tracking-tight">
                {isView ? 'View Party Master' : isAdd ? 'Add Party Master' : 'Edit Party Master'}
              </h2>
              <p className="text-sm font-medium text-slate-500 mt-0.5">
                {form.partyCode || 'Party code will be generated automatically'}
              </p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={onBack}
              className="flex items-center justify-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-slate-600 border border-slate-200 bg-white hover:bg-slate-50 transition-all"
            >
              <X size={16} />
              Back
            </button>
            {!isView && (
              <button
                type="submit"
                form="party-master-page-form"
                className="btn-primary flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-white shadow-lg shadow-emerald-500/30"
              >
                <Save size={16} />
                {isAdd ? 'Create Party' : 'Save Changes'}
              </button>
            )}
          </div>
        </div>

        <form id="party-master-page-form" onSubmit={submit} className="p-6">
          <div className="flex flex-col gap-7">
            {groupedFields.map(group => (
              <section key={group.section} className="border-b border-slate-100 last:border-b-0 pb-7 last:pb-0">
                <div className="flex items-center gap-3 mb-4">
                  <div className="h-8 w-8 rounded-xl bg-emerald-50 border border-emerald-100 flex items-center justify-center">
                    <Tag size={15} className="text-emerald-600" />
                  </div>
                  <h3 className="text-sm font-black text-slate-700 uppercase tracking-widest">{group.section}</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
                  {group.fields.map(field => (
                    <FormField
                      key={field.key}
                      field={field}
                      value={form[field.key]}
                      onChange={set}
                      disabled={isView}
                      error={errors[field.key]}
                    />
                  ))}
                </div>
              </section>
            ))}
          </div>

          {!isView && (
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-end gap-3 mt-8 pt-6 border-t border-slate-100">
              <button
                type="button"
                onClick={onBack}
                className="flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-slate-600 border border-slate-200 bg-white hover:bg-slate-50 transition-all"
              >
                <X size={16} />
                Cancel
              </button>
              <button
                type="submit"
                className="btn-primary flex items-center justify-center gap-2 px-8 py-3 rounded-xl text-sm font-bold text-white shadow-lg shadow-emerald-500/30"
              >
                <Save size={16} />
                {isAdd ? 'Create Party' : 'Save Changes'}
              </button>
            </div>
          )}
        </form>
      </div>
    </div>
  );
}

export default function PartyMasterPage() {
  const {
    partyMasterItems,
    partyMasterSearchQuery,
    partyMasterTypeFilter,
    partyMasterMsmeFilter,
    partyMasterCurrentPage,
    partyMasterItemsPerPage,
    setPartyMasterSearchQuery,
    setPartyMasterTypeFilter,
    setPartyMasterMsmeFilter,
    setPartyMasterCurrentPage,
    setPartyMasterItemsPerPage,
    deletePartyMaster,
    getFilteredPartyMasterItems,
    getPartyMasterStats,
  } = useERPStore();
  const [viewState, setViewState] = useState({ type: 'table', mode: null, party: null });
  const [deleteCandidateId, setDeleteCandidateId] = useState(null);

  const filtered = getFilteredPartyMasterItems();
  const stats = getPartyMasterStats();
  const totalPages = Math.ceil(filtered.length / partyMasterItemsPerPage);
  const pagedPartys = filtered.slice(
    (partyMasterCurrentPage - 1) * partyMasterItemsPerPage,
    partyMasterCurrentPage * partyMasterItemsPerPage
  );

  const partyTypes = useMemo(() => {
    return ['All', ...Array.from(new Set(partyMasterItems.map(party => party.partyType).filter(Boolean))).sort()];
  }, [partyMasterItems]);

  const msmeTypes = useMemo(() => {
    return ['All', ...Array.from(new Set(partyMasterItems.map(party => party.msmeEnterpriseType).filter(Boolean))).sort()];
  }, [partyMasterItems]);

  const openForm = (mode, party = null) => {
    setDeleteCandidateId(null);
    setViewState({ type: 'form', mode, party });
  };

  const backToTable = () => setViewState({ type: 'table', mode: null, party: null });

  const clearFilters = () => {
    setPartyMasterSearchQuery('');
    setPartyMasterTypeFilter('All');
    setPartyMasterMsmeFilter('All');
  };

  const exportCsv = () => {
    const headers = PARTY_MASTER_FIELDS.map(field => field.label);
    const rows = filtered.map(party => PARTY_MASTER_FIELDS.map(field => String(party[field.key] ?? '').replaceAll('"', '""')));
    const csv = [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'party-master.csv';
    link.click();
    URL.revokeObjectURL(url);
  };

  const renderCellValue = (party, column) => {
    const value = party[column.key];

    if (column.key === 'partyCode') {
      return (
        <span className="inline-flex items-center gap-1.5 text-emerald-700 font-bold bg-emerald-50 px-2.5 py-1 rounded-md border border-emerald-200 whitespace-nowrap">
          <Hash size={12} /> {value || '-'}
        </span>
      );
    }

    if (column.key === 'partyName') {
      return <span className="font-bold text-slate-800 line-clamp-2" title={value}>{value || '-'}</span>;
    }

    if (column.key.endsWith('Email')) {
      return value ? (
        <span className="inline-flex items-center gap-1.5 max-w-[220px] truncate text-indigo-700" title={value}>
          <Mail size={12} /> {value}
        </span>
      ) : '-';
    }

    if (column.key.endsWith('ContactNo')) {
      return value ? (
        <span className="inline-flex items-center gap-1.5 text-slate-700 whitespace-nowrap" title={value}>
          <Phone size={12} /> {value}
        </span>
      ) : '-';
    }

    if (column.key === 'msmeEnterpriseType') {
      const isApplicable = value && value !== 'Not Applicable';
      return (
        <span className={`inline-flex px-2.5 py-1 rounded-full text-[11px] font-bold border ${isApplicable
            ? 'bg-amber-50 text-amber-700 border-amber-200'
            : 'bg-slate-100 text-slate-500 border-slate-200'
          }`}>
          {value || 'Not Applicable'}
        </span>
      );
    }

    if (column.type === 'select') {
      return (
        <span className="inline-flex px-2.5 py-1 rounded-full text-[11px] font-bold border bg-emerald-50 text-emerald-700 border-emerald-200">
          {value || '-'}
        </span>
      );
    }

    if (column.type === 'date') {
      return <span className="font-semibold text-slate-700 whitespace-nowrap">{value || '-'}</span>;
    }

    return <span className="block max-w-[240px] truncate" title={value}>{value || '-'}</span>;
  };

  return (
    <div className="p-3 max-w-[1920px] mx-auto animate-slide-up">
      {viewState.type !== 'form' && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <StatsCard label="Total Parties" value={stats.total.toLocaleString()} icon={Building2} color="#10b981" bg="rgba(16,185,129,0.12)" border="rgba(16,185,129,0.25)" animationDelay={0} />
          <StatsCard label="Party Types" value={stats.types.toLocaleString()} icon={BriefcaseBusiness} color="#6366f1" bg="rgba(99,102,241,0.12)" border="rgba(99,102,241,0.25)" animationDelay={50} />
          <StatsCard label="MSME Partys" value={stats.msme.toLocaleString()} icon={BadgeCheck} color="#f59e0b" bg="rgba(245,158,11,0.12)" border="rgba(245,158,11,0.25)" animationDelay={100} />
          <StatsCard label="This Month" value={stats.enrolledThisMonth.toLocaleString()} icon={CalendarDays} color="#ef4444" bg="rgba(239,68,68,0.12)" border="rgba(239,68,68,0.25)" animationDelay={150} />
        </div>
      )}


      {viewState.type === 'form' ? (
        <PartyMasterForm mode={viewState.mode} party={viewState.party} onBack={backToTable} />
      ) : (
        <>
          <div className="glass-card rounded-2xl p-5 shadow-xl mb-6">
            <div className="flex flex-col xl:flex-row gap-4 items-center">
              <div className="relative flex-1 w-full min-w-0 group">
                <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-emerald-500 transition-colors" />
                <input
                  type="text"
                  placeholder="Search by party code, party name, GST, PAN, contact..."
                  value={partyMasterSearchQuery}
                  onChange={event => setPartyMasterSearchQuery(event.target.value)}
                  className="w-full pl-11 pr-4 py-3 text-sm input-glow rounded-xl focus:border-emerald-500/50"
                />
              </div>

              <div className="flex flex-wrap gap-3 w-full xl:w-auto">
                <select
                  value={partyMasterTypeFilter}
                  onChange={event => setPartyMasterTypeFilter(event.target.value)}
                  className="px-4 py-3 text-sm rounded-xl text-slate-600 border border-slate-200 bg-white hover:bg-slate-50 focus:border-emerald-500/50 transition-all outline-none cursor-pointer"
                >
                  {partyTypes.map(type => <option key={type} value={type}>{type === 'All' ? 'All Party Types' : type}</option>)}
                </select>
                <select
                  value={partyMasterMsmeFilter}
                  onChange={event => setPartyMasterMsmeFilter(event.target.value)}
                  className="px-4 py-3 text-sm rounded-xl text-slate-600 border border-slate-200 bg-white hover:bg-slate-50 focus:border-emerald-500/50 transition-all outline-none cursor-pointer"
                >
                  {msmeTypes.map(type => <option key={type} value={type}>{type === 'All' ? 'All MSME Types' : type}</option>)}
                </select>
              </div>

              <div className="flex gap-3 w-full xl:w-auto shrink-0">
                <button onClick={exportCsv} className="flex items-center justify-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-slate-600 border border-slate-200 bg-white hover:bg-slate-50 transition-all flex-1 xl:flex-none">
                  <FileDown size={18} />
                  Export
                </button>
                <button onClick={() => openForm('add')} className="btn-primary flex items-center justify-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-white shadow-lg shadow-emerald-500/30 flex-1 xl:flex-none">
                  <Plus size={18} strokeWidth={2.5} />
                  Add Party
                </button>
              </div>
            </div>

            <div className="flex items-center justify-between mt-4 px-1">
              <p className="text-xs font-medium text-slate-500">
                Showing <span className="text-slate-800 font-bold px-1">{filtered.length}</span> of <span className="text-slate-800 font-bold px-1">{partyMasterItems.length}</span> partys
              </p>
              {(partyMasterSearchQuery || partyMasterTypeFilter !== 'All' || partyMasterMsmeFilter !== 'All') && (
                <button onClick={clearFilters} className="flex items-center gap-1.5 text-xs font-bold text-emerald-600 hover:text-emerald-700 bg-emerald-50 hover:bg-emerald-100 px-3 py-1.5 rounded-lg transition-colors">
                  <RefreshCw size={12} /> Clear Filters
                </button>
              )}
            </div>
          </div>

          <div className="glass-card rounded-2xl overflow-hidden shadow-2xl pb-4">
            <Table>
              <Table.ScrollContainer>
                <Table.Content
                  aria-label="Party master table"
                  className="text-left"
                  style={{ minWidth: `${TABLE_COLUMNS.length * 175 + 150}px` }}
                >
                  <Table.Header>
                    <Table.Column isRowHeader className="w-28 whitespace-nowrap">
                      Actions
                    </Table.Column>
                    {TABLE_COLUMNS.map(column => (
                      <Table.Column
                        key={column.key}
                        className="whitespace-nowrap"
                        style={{ minWidth: column.width, textAlign: column.align || 'left' }}
                      >
                        {column.label}
                      </Table.Column>
                    ))}
                  </Table.Header>
                  <Table.Body items={pagedPartys} renderEmptyState={() => (
                    <div className="py-24 text-center text-slate-500">
                      <div className="flex flex-col items-center gap-4">
                        <div className="p-4 rounded-full bg-slate-50 border border-slate-200">
                          <SlidersHorizontal size={32} className="text-slate-400" />
                        </div>
                        <p className="text-sm font-medium">No partys found. Try adjusting your filters.</p>
                      </div>
                    </div>
                  )}>
                    {(party) => (
                      <Table.Row key={party.id} className="group">
                        <Table.Cell>
                          {deleteCandidateId === party.id ? (
                            <div className="flex items-center gap-2">
                              <button
                                onClick={() => {
                                  deletePartyMaster(party.id);
                                  setDeleteCandidateId(null);
                                }}
                                className="px-3 py-1.5 rounded-lg text-xs font-bold text-white bg-red-600 hover:bg-red-700 transition-all"
                              >
                                Delete
                              </button>
                              <button
                                onClick={() => setDeleteCandidateId(null)}
                                className="px-3 py-1.5 rounded-lg text-xs font-bold text-slate-600 border border-slate-200 hover:bg-slate-50 transition-all"
                              >
                                Cancel
                              </button>
                            </div>
                          ) : (
                            <div className="flex items-center gap-1.5 opacity-0 translate-y-1 pointer-events-none transition-all duration-200 group-hover:opacity-100 group-hover:translate-y-0 group-hover:pointer-events-auto group-focus-within:opacity-100 group-focus-within:translate-y-0 group-focus-within:pointer-events-auto">
                              <button onClick={() => openForm('view', party)} className="p-2 rounded-lg text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 hover:shadow-[0_0_10px_rgba(99,102,241,0.2)] transition-all" title="View">
                                <Eye size={15} />
                              </button>
                              <button onClick={() => openForm('edit', party)} className="p-2 rounded-lg text-slate-400 hover:text-amber-600 hover:bg-amber-50 hover:shadow-[0_0_10px_rgba(245,158,11,0.2)] transition-all" title="Edit">
                                <Edit size={15} />
                              </button>
                              <button onClick={() => setDeleteCandidateId(party.id)} className="p-2 rounded-lg text-slate-400 hover:text-red-600 hover:bg-red-50 hover:shadow-[0_0_10px_rgba(239,68,68,0.2)] transition-all" title="Delete">
                                <Trash2 size={15} />
                              </button>
                            </div>
                          )}
                        </Table.Cell>
                        {TABLE_COLUMNS.map(column => (
                          <Table.Cell key={column.key} className="text-[13px] text-slate-700" style={{ textAlign: column.align || 'left' }}>
                            {renderCellValue(party, column)}
                          </Table.Cell>
                        ))}
                      </Table.Row>
                    )}
                  </Table.Body>
                </Table.Content>
              </Table.ScrollContainer>
            </Table>

            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 px-6 pt-4 border-t border-slate-100">
              <div className="flex items-center gap-3 text-sm font-medium text-slate-500">
                <span>Rows per page:</span>
                <select
                  value={partyMasterItemsPerPage}
                  onChange={event => setPartyMasterItemsPerPage(Number(event.target.value))}
                  className="px-3 py-1.5 rounded-lg text-slate-700 bg-white border border-slate-200 outline-none focus:border-emerald-500/50 hover:bg-slate-50 transition-colors cursor-pointer"
                >
                  {[10, 20, 50, 100].map(count => <option key={count} value={count}>{count}</option>)}
                </select>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => setPartyMasterCurrentPage(Math.max(1, partyMasterCurrentPage - 1))}
                  disabled={partyMasterCurrentPage === 1}
                  className="px-4 py-2 text-sm font-medium rounded-xl text-slate-600 bg-white border border-slate-200 hover:bg-slate-50 disabled:opacity-30 disabled:cursor-not-allowed transition-all"
                >
                  Previous
                </button>

                <div className="flex items-center gap-1 hidden sm:flex">
                  {Array.from({ length: Math.min(5, totalPages || 1) }, (_, index) => {
                    let page;
                    if (totalPages <= 5) page = index + 1;
                    else if (partyMasterCurrentPage <= 3) page = index + 1;
                    else if (partyMasterCurrentPage >= totalPages - 2) page = totalPages - 4 + index;
                    else page = partyMasterCurrentPage - 2 + index;

                    return (
                      <button
                        key={page}
                        onClick={() => setPartyMasterCurrentPage(page)}
                        className={`w-10 h-10 text-sm rounded-xl transition-all font-bold ${partyMasterCurrentPage === page
                            ? 'text-white bg-emerald-600 border border-emerald-500 shadow-lg shadow-emerald-500/30'
                            : 'text-slate-600 bg-white border border-slate-200 hover:bg-slate-50'
                          }`}
                      >
                        {page}
                      </button>
                    );
                  })}
                </div>

                <button
                  onClick={() => setPartyMasterCurrentPage(Math.min(totalPages, partyMasterCurrentPage + 1))}
                  disabled={partyMasterCurrentPage === totalPages || totalPages === 0}
                  className="px-4 py-2 text-sm font-medium rounded-xl text-slate-600 bg-white border border-slate-200 hover:bg-slate-50 disabled:opacity-30 disabled:cursor-not-allowed transition-all"
                >
                  Next
                </button>
              </div>

              <p className="text-sm font-medium text-slate-500">
                Page <span className="text-slate-800 bg-slate-100 px-2 py-0.5 rounded-md">{partyMasterCurrentPage}</span> of{' '}
                <span className="text-slate-800">{totalPages || 1}</span>
              </p>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
